font_family Agave Regular

shell_integration no-cursor
cursor_shape beam

window_padding_width  10
window_padding_height 10

font_size 14

background_opacity 1

cursor               #6485BE

selection_background #C69A8E
selection_foreground #1D2331

background           #1D2331
foreground           #C69A8E
